language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake
script:
  - mkdir build && cd build
  - cmake ..
  - make
